# Jekyll config file
source: ""

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
