# Jekyll config file

title: "Development Cheat Sheets"
# The root folder of the website
source: ""
# baseurl for a site that doesn’t sit at the root of the domain
# See: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: /development-cheat-sheets

#repository: ben-kemister.github.io/development-cheat-sheets/
#repository: https://github.com/ben-kemister/development-cheat-sheets

# This works!!!
repository: ben-kemister/development-cheat-sheets
# TODO need to look at warning: GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

theme: jekyll-theme-cayman

# https://goharsha.com/blog/jekyll-trick-implementing-devmode-and-livereload/
development: false

# Note: Most/All plugins will not work on GitHub pages
# plugins:
#   - jekyll-seo-tag

collections:
  tag:
    output: true
  languages:
    output: true
  frameworks:
    output: true
  tools:
    output: true
  operating_systems:
    output: true

defaults:
  # Site Defaults
  - scope:
      path: ""
    values:
      layout: "default"
      excerpt_separator: "<!--more-->"
      showTOC: false
  # (Programming) Languages
  - scope:
      path: "_languages/*"
    values:
      layout: language
      pageLevel: 1
  - scope:
      path: "_languages/*/*"
    values:
      layout: page_with_tags
      showTOC: true
      pageLevel: 2
  - scope:
      path: "_languages/java/*"
    values:
      language: java
      category: java
      tags: java
  - scope:
      path: "_languages/javascript/*"
    values:
      language: javascript
      category: javascript
      tags: javascript
  - scope:
      path: "_languages/sql/*"
    values:
      language: sql
      category: sql
      tags: sql
  - scope:
      path: "_languages/typescript/*"
    values:
      language: typescript
      category: typescript
      tags: typescript
  - scope:
      path: "_languages/html/*"
    values:
      language: html
      category: html
      tags: html
  - scope:
      path: "_languages/python/*"
    values:
      language: python
      category: python
      tags: python
  # Tools pages
  - scope:
      path: ""
      type: tools
    values:
      # We want to make sure that we get a header on these pages
      layout: page_with_tags
  # Tag pages
  - scope:
      path: ""
      type: tag
    values:
      layout: tagpage
  # Operating System pages
  - scope:
      path: ""
      type: operating_systems
    values:
      layout: page_with_tags

