# Jekyll config file
title: "Developer Cheat Sheets"
source: "" # The root folder of the website

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

theme: jekyll-theme-cayman

collections:
  languages:
    output: true
  javascript:
    output: true

defaults:
  - scope:
      path: ""
      type: languages
    values:
      layout: language
  - scope:
      path: ""
      type: javascript
    values:
      language: javascript
  - scope:
      path: ""
    values:
      layout: "default"
  