# Jekyll config file
title: "Developer Cheat Sheets"
source: "" # The root folder of the website

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
