# Jekyll config file

title: "Developer Cheat Sheets"
# The root folder of the website
source: ""
# baseurl for a site that doesn’t sit at the root of the domain
# See: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: /development-cheat-sheets

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

theme: jekyll-theme-cayman

collections:
  languages:
    output: true
  javascript:
    output: true
  typescript:
    output: true
  tools:
    output: true

defaults:
  - scope:
      path: ""
      type: languages
    values:
      layout: language
  - scope:
      path: ""
      type: javascript
    values:
      language: javascript
  - scope:
      path: ""
      type: typescript
    values:
      language: typescript
  - scope:
      path: ""
    values:
      # layout: "default"
      layout: "myDefault"
      showTOC: true
  